
name: 'dbt_ecommerce_project'
version: '1.0.0'
config-version: 2

profile: 'dbt_ecommerce_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


seeds:
  product_category_name_translation:
    +column_types:
      product_category_name: varchar(1000)
      product_category_name_english: varchar(1000)
    +materialized: table
    +delimiter: ","

models:
  dbt_ecommerce_project:
    needed_cols:
      +materialized: view
    data_types:
     +materialized: table
    charts:
      +materialized: table
