
name: 'dbt_ecommerce_project'
version: '1.0.0'
config-version: 2

profile: 'dbt_ecommerce_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" 
clean-targets:        
  - "target"
  - "dbt_packages"

on-run-start:
  - "insert into {{ source('ecommerce_database', 'run_log') }} (start_time, status_check) values (current_timestamp, 'started');"

on-run-end:
  - "insert into {{ source('ecommerce_database', 'run_log') }} (start_time, status_check) values (current_timestamp, 'completed');"

seeds:
  product_category_name_translation:
    +column_types:
      product_category_name: varchar(1000)
      product_category_name_english: varchar(1000)
    +materialized: table
    +delimiter: ","

models:
  dbt_ecommerce_project:
    needed_cols:
      +materialized: view
    data_types:
     +materialized: table
    charts:
      +materialized: table
