version: 2

models:
  - name: nc_customers
    columns:
      - name: customerId
        tests:
          - unique
          - not_null
  - name: nc_orders
    columns:
      - name: customerId
        tests:
          - relationships:
              to: ref('nc_customers')
              field: customerId
      - name: orderId
        tests:
          - unique
          - not_null
      - name: orderStatus
        tests:
          - accepted_values:
              values: ['delivered', 'invoiced', 'shipped', 'processing', 'unavailable', 'cancelled', 'created', 'approved']