version: 2

sources:
  - name: ecommerce_database
    database: ecommerce_database  
    schema: ecommerce_database  
    tables:
      - name: orders
      - name: customers
      - name: order_items
      - name: payments
      - name: sellers
      - name: reviews
      - name: products
      - name: run_log